server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quotes_core
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/changelog.xml
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
jwt:
  secretKey: secreteeffffffffffffffffffffffffffffffffffffffffffaf
kafka:
  bootstrap: localhost:29092
  groupId: quote-core
  userInfoTopic: user
