server:
  port: ${APPLICATION_PORT}
spring:
  datasource:
    url: ${DATASOURCE_URL}
    driverClassName: ${JDBC_DRIVER_CLASS_NAME}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog.xml
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none

jwt:
  expiration: ${JWT_EXPIRATION_IN_MINUTES}
  secret: ${JWT_SECRET}

kafka:
  bootstrap: ${KAFKA_BOOTSTRAP}